-- MySQL Script generated by MySQL Workbench
-- Sat Jun 23 14:36:44 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Kong
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Kong
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Kong` DEFAULT CHARACTER SET utf8 ;
USE `Kong` ;

-- -----------------------------------------------------
-- Table `Kong`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Kong`.`Login` (
  `UserID` INT NOT NULL AUTO_INCREMENT COMMENT 'Surrogate key',
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UserID`),
  UNIQUE INDEX `UserID_UNIQUE` (`UserID` ASC),
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Kong`.`Sensor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Kong`.`Sensor` (
  `SensorID` INT NOT NULL AUTO_INCREMENT COMMENT 'Surrogate key',
  `SensorTemperature` DECIMAL(5,3) NOT NULL COMMENT '17.569 degreesC ',
  `SensorHumidity` DECIMAL(5,4) NOT NULL COMMENT '98.52% = 0.9852',
  `SensorDT` DATETIME(0) NOT NULL COMMENT '2018-06-23 14:50:49',
  PRIMARY KEY (`SensorID`),
  UNIQUE INDEX `SensorID_UNIQUE` (`SensorID` ASC),
  UNIQUE INDEX `SensorDT_UNIQUE` (`SensorDT` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
