-- MySQL Script generated by MySQL Workbench
-- Tue Jun 26 12:02:02 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema kong
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kong
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kong` DEFAULT CHARACTER SET utf8 ;
USE `kong` ;

-- -----------------------------------------------------
-- Table `kong`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kong`.`Login` (
  `UserID` INT NOT NULL AUTO_INCREMENT COMMENT 'Surrogate key',
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UserID`),
  UNIQUE INDEX `UserID_UNIQUE` (`UserID` ASC),
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kong`.`Sensor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kong`.`Sensor` (
  `SensorID` INT NOT NULL AUTO_INCREMENT COMMENT 'Surrogate key',
  `SensorTemperature` DECIMAL(5,3) NOT NULL COMMENT '17.569 degreesC ',
  `SensorHumidity` DECIMAL(5,4) NOT NULL COMMENT '98.52% = 0.9852',
  `SensorDT` DATETIME(0) NOT NULL,
  PRIMARY KEY (`SensorID`),
  UNIQUE INDEX `SensorID_UNIQUE` (`SensorID` ASC),
  UNIQUE INDEX `SensorDT_UNIQUE` (`SensorDT` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kong`.`Purchase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kong`.`Purchase` (
  `PurchaseID` INT NOT NULL AUTO_INCREMENT COMMENT 'Surrogate key',
  `Email` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `CreditCard` VARCHAR(19) NOT NULL,
  `ShippingAddress` VARCHAR(45) NOT NULL,
  `ZipCode` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`PurchaseID`),
  UNIQUE INDEX `PurchaseID_UNIQUE` (`PurchaseID` ASC),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
